language: node_js
node_js:
  - "node"
os:
  - linux

install:
  - npm install
  - npm install -g vsce

script:
  - vsce package

deploy:
  provider: script
  script: echo vsce publish -p ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }} | bash
  skip_cleanup: true
  # on:
    # tags: true
    # condition: "$TRAVIS_TAG =~ ^v"
