language: node_js
node_js:
  - "node"
os:
  - linux

install:
  - npm install
  - npm install -g vsce

script:
  - vsce package

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    tags: true
    # condition: "$TRAVIS_TAG =~ ^v"
